default_language_version:
  python: python3

default_stages: [commit, push]

repos:
- repo: https://github.com/aws-cloudformation/cfn-python-lint
  rev: v0.55.0 
  hooks:
    - id: cfn-python-lint
      files: templates/.*\.(json|yml|yaml)$