name: Deploy website to S3
on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Upload files to S3 with AWS CLI
      run: |
        aws s3 sync ${{ secrets.PROJECT_FOLDER }} s3://${{ secrets.AWS_BUCKET }} --delete 